name: Run API Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ui_tests:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Start App
        run: node index.js &
        env:
          NODE_ENV: production

      - name: Wait for App to Start
        run: |
          for i in {1..30}; do
            if curl --silent --fail -k https://localhost:3000/health; then
              echo "App is up and running!"
              exit 0
            fi
            echo "Waiting for app to start..."
            sleep 2
          done
          echo "App failed to start in time."
          exit 1

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests
        run: newman run ./tests/DCC_OIDF.postman_collection.json --insecure
